### ISSUE TITLE
Necessity of constant-time encoding for PathORAM buckets of arbitrary size?

### ISSUE THREAD

**Issue by holycleugh** [cloudflare/utahfs#15]
Hi,
This is more of a theoretical question, rather than a real attack proposal. In the Path ORAM paper, they note that each bucket is padded to the maximum number of blocks so the server can't tell which of the buckets in the path have the "real" blocks, which might allow correlation attacks.

But the marshalling function here https://github.com/cloudflare/utahfs/blob/master/persistent/oblivious.go#L18-L60 does not process buckets in constant-time. My questions are 1) is this attack of theoretical importance? and 2) is this attack of any practical importance, or do network latencies completely mitigate any issues here? Especially because (from a brief glance) there seems to only be 4 blocks per bucket.

**Comment by Bren2010** [comment]
Right, the marshalling function is fast enough that I can't see a timing attack being practical here. I can't say whether or not it's theoretically meaningful.
