### ISSUE TITLE
Metadata size

### ISSUE THREAD

**Issue by FlorentCoppint** [cloudflare/utahfs#17]
Hi,
I'm testing UtahFS with 1M block size, with various files for around 60GB.
My metadata file is 6GB large, is it expected ? Is there a way to optimize it ?
Thank you.
Florent

**Comment by Bren2010** [comment]
1M is quite a large block size and can result in a lot of waste when storing inodes. If I'm doing the math correctly, I'd guess you have ~5k files that are ~10MB each?

My first recommendation would be to start your archive over with a smaller block size, and the metadata file will be proportionally smaller.

If that's not possible, you can set `keep-metadata` to `false` in your config and delete the `metadata` file. Metadata (like inodes and integrity information) won't be cached anymore which has a performance impact, but you can keep your large block size with a smaller client-side footprint.

**Comment by FlorentCoppint** [comment]
Thank you @Bren2010 , in my mind : larger block size = less blocks = less metadata.
What are "metadata" exactly in UtahFS ?

**Comment by Bren2010** [comment]
All in all, metadata includes:
- The [State](https://github.com/cloudflare/utahfs/blob/master/persistent/app_storage.go#L17) struct (constant size).
- The [root of the Merkle tree](https://github.com/cloudflare/utahfs/blob/master/persistent/integrity.go#L21) (constant size).
- Intermediate nodes in the Merkle tree (proportional to the number of blocks, but quite small).
- Inode data (~1 block per file / folder).

So inodes are the dominant source of metadata.
