### ISSUE TITLE
Configuration to specify directory within bucket to connect to

### ISSUE THREAD

**Issue by balupton** [cloudflare/utahfs#18]
I would like the S3 connection to write to a specific folder within the bucket, so that I can control which storage class is used (as it seems S3 only lets me specify the storage class for s3 glacier vaults, which are not buckets; or in the case of buckets, only for specific folders rather than for the entire bucket).

When I omit the URL, it writes to the root directory (as expected).

However, when I add a URL, like `folder-name`, or `/folder-name`, or `folder-name/`, or `/folder-name/`, it doesn't seem to work. I even tried: `https://bucket.s3.amazonaws.com/folder/` but that resulted in a weird situation where the data was written to `bucket/folder/folder-with-bucket-name/*`

So which URL styles from http://www.wryway.com/blog/aws-s3-url-styles/ are supported?

And how can I configure it to write to a specific directory on the cloud storage?

**Comment by Bren2010** [comment]
The attached commit should give you a way to do this.
