### ISSUE TITLE
Cloudflare Workers KV

### ISSUE THREAD

**Issue by balupton** [cloudflare/utahfs#2]
I see s3 as one if the options, however what about cloudflare workers KV.

Secondly, how does one go about adding support for more? IPFS pinning services would also be nice

**Comment by Bren2010** [comment]
You could theoretically use Workers KV, but that product is significantly more expensive than any other storage provider. It's designed for high speed data access, but you won't see any advantage from that over the Internet.

To add a new backend, you would add a file to the `persistent/` folder with an implementation of the `ObjectStorage` interface that does what you want. Then add some wiring to `cmd/internal/config/config.go` to let your implementation be setup from a config file.
