### ISSUE TITLE
integrity: block does not equal expected value

### ISSUE THREAD

**Issue by FlorentCoppint** [cloudflare/utahfs#22]
Hi,
After a forced unmount due to blocked I/O, I can't remount my UtahFS. Got this error : 
integrity: block does not equal expected value
All my data is lost ?
Thank you.

**Comment by Bren2010** [comment]
Did you ever delete the local `.utahfs` folder or anything in it?

**Comment by FlorentCoppint** [comment]
Yes I did 😐 all was frozen, so I tried deleting it.
But can't we mount an existing UtahFS without .utahfs dir ?

**Comment by Bren2010** [comment]
Unfortunately not always. I've documented [this](https://github.com/cloudflare/utahfs/tree/master/docs#important-note-on-locally-stored-data) in the README now, but the `.utahfs` directory likely contained data that hadn't been uploaded yet.
