### ISSUE TITLE
Failed to Initialize Storage

### ISSUE THREAD

**Issue by ashaney** [cloudflare/utahfs#25]
I'm testing out the single client implementation on MacOS Catalina 10.15.5. I believe I have my B2 configuration set up properly in the yaml config file, but it's possible I am missing something. When I try to run utahfs-client, I receive the following error:

`main.go:43: failed to initialize storage: sql: Scan error on column index 0, name "MAX(rowid)": converting NULL to int64 is unsupported`

I have go 1.14.4 installed and I am using a public S3 B2 bucket for storage. When I ran `go get` it dropped `go/bin/utahfs` in my home directory. I entered that directory, created my .yaml config, and created an empty folder named utahfs. It is reading the config file when I run `./utahfs-client`, but I wonder if there is something configured improperly on my end.

UPDATE: I tried this on an ARM device running Ubuntu and additionally on MacOS with the local settings and I still received the same error.

**Comment by Bren2010** [comment]
This should be fixed by the attached commit, thank you for reporting!
