### ISSUE TITLE
How much needs to be downloaded to know what is what? And is it cached?

### ISSUE THREAD

**Issue by balupton** [cloudflare/utahfs#27]
I'm thinking of using UtahFS for a backup use case (storage of 2+TB of data, with intended retrieval of 1TB of data about once a year), using one of the following providers:

- [AWS’s Glacier Deep Archive](https://aws.amazon.com/blogs/aws/new-amazon-s3-storage-class-glacier-deep-archive/) which is about $1/TB/month/storage [180 day minimum](https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html#sc-glacier) and $20.50/TB/access ($2.50/TB for bulk access, 48 hour wait time for retrieval) — [calculator](https://calculator.aws/#/createCalculator)

- [Google's Archive](https://cloud.google.com/blog/products/storage-data-transfer/archive-storage-class-for-coldest-data-now-available) which is about $1.23/TB/month/storage and $51.20/TB/access — [calculator](https://cloud.google.com/products/calculator#id=34cb8c4e-05e4-4072-b1d4-80b421e3baa5)

Which have much cheaper storage costs, but much more expensive access costs compared to the more typical tiers.

As such, how much would UtahFS need to download to know what is what per TB of data, and does it cache this "table of contents" knowledge so it doesn't have to be downloaded each boot?

One other consideration here is that these archival storage classes generally require a minimum lease on the data storage (so you upload a file, and you pay for a minimum of 6 months of storage of that file) — as such, UtahFS shouldn't change files unless absolutely necessary.

**Comment by FlorentCoppint** [comment]
Hi,

You can't use UtahFS with such services, it is not built to work on this.
To explain simple, when using UtahFS, the objects on S3 service must be always available. When using Glacier-like backend service, objects are not available immediately, they have to be "restored", this operation takes time.

**Comment by Bren2010** [comment]
Florent is right, and I should also say that 2 TB of data is a relatively small amount. You'd be just as well using standard object storage providers: 2 TB on Backblaze = $10/mo

To answer the question you asked: Assuming you're not using ORAM, there's one "inode" object per file or folder which contains metadata about that file/folder. To access a file, you need to access the inodes for each directory on the way to the file, and the inode for the file itself. So the overhead is proportional to your directory structure.

**Comment by balupton** [comment]
Ok, that clears things up. Thanks for the information.
