### ISSUE TITLE
Local WAL drain returns SQL error: no rows in result set

### ISSUE THREAD

**Issue by wilsonehusin** [cloudflare/utahfs#36]
I'm running single-device setup on `master` branch (3b886c6d7f9530d4c4a3b28511bb847d0be1a0f7 at the moment) with GCS as storage backend on NixOS unstable desktop.

Upon running `utahfs-client ...`, this line shows up every 5 seconds in the log:
```
DATETIME local_wal.go:93: sql: no rows in result set
```

which seems to point at:
https://github.com/cloudflare/utahfs/blob/3b886c6d7f9530d4c4a3b28511bb847d0be1a0f7/persistent/local_wal.go#L83-L96

I'm guessing this is a result of not having anything to sync with the storage provider, though I could be wrong. Is this an expected behavior?

Edit: clarifying, seems like data storage/retrieval is working with a light minimal test (`echo "hello world" > hello.txt` seem to be persistent throughout restarts etc.) though I'd like to hear more from maintainers if this is a good enough sign to start relying on this storage.

**Comment by Bren2010** [comment]
No, this isn't an expected behavior. I suspect it might be related to the SQLite driver which was recently changed. Can you update to the current master (which reverts the change) and see if it still happens?

**Comment by wilsonehusin** [comment]
Rebuilt on 2c2be7936f92b415f22d5c4166522fc78bcda3b4 and it seem to work fine now!

**Comment by Bren2010** [comment]
Awesome, thank you :)
