### ISSUE TITLE
UtahFS request rate & retries

### ISSUE THREAD

**Issue by FlorentCoppint** [cloudflare/utahfs#37]
Hi,
I'm using UtahFS with Scaleway S3 service.
Sometimes I got errors like this :

2020/10/12 15:23:51 local_wal.go:93: ServiceUnavailable: Please reduce your request rate.
status code: 503, request id: tx3b4bf240a63a479a9a0cd-005f8458be, host id: tx3b4bf240a63a479a9a0cd-005f8458be

My S3 provider limits request to 250 per second per bucket. They don't want to set higher limits.

Does UtahFS handle such case ? Will requests be retried later if some failed ?

Thank you.

**Comment by Bren2010** [comment]
Yes, requests will be retried later. If the error messages themselves are the issue and you've set the `wal-parallelism` value higher than 1, you could reduce it to lower the request rate.
