### ISSUE TITLE
Unable to mount, no error

### ISSUE THREAD

**Issue by FlorentCoppint** [cloudflare/utahfs#38]
Hi,

I'm using UtahFS on a Debian Buster box.
I'm unable to have a stable filesystem. Sometimes it freezes, self unmount ...

And now, it doesn't want to mount anymore !

I run :
`utahfs-client -cfg backup-nas-utahfs.yaml -mount backup-nas-utahfs/ -v`

And nothing happen anymore, no error displayed, no directory mounted... Command still run.

Nothing has changed in configuration, I always have .utahfs directory with metadata, pin & wal and S3 server is reachable.

How can I debug this ? How to get a stable file system ?

For information, config contains S3 data + : 
```
keep-metadata: true
wal-parallelism: 4
disk-cache-size: -1
mem-cache-size: -1
archive: false
oram: false
```

**Comment by FlorentCoppint** [comment]
Using tcpdump, I can see UtahFS-client doing some S3 requests (https encrypted, I can't read them). Will it read/request the 5M+ objects it created ?!

**Comment by FlorentCoppint** [comment]
Sorry for the noise, problem was on my S3 provider side ...

**Comment by Bren2010** [comment]
Glad you figured it out! Sorry for the delay
