### ISSUE TITLE
[Feature Request] Add an option to make it run as a daemon.

### ISSUE THREAD

**Issue by mhogomchungu** [cloudflare/utahfs#6]
Nothing to add here.

**Comment by agowa338** [comment]
Why not just use systemd with "Type=simple"? Should work just fine.

**Comment by mhogomchungu** [comment]
This feature together with the other one I requested are the bare minimum necessary in order to support utahfs in my project as requested here[1]

[1] https://github.com/mhogomchungu/sirikali/issues/152

**Comment by agowa338** [comment]
Couldn't you just use shell wrapper (potentially with nohup, depending how you want to run it) for that?
e.g.:
```
#!/bin/sh
nohup utahfs-client -cfg ./utahfs.yaml -mount ./utahfs &
```

**Comment by mhogomchungu** [comment]
It's possible to do all sort of things but why?, this project is based on fuse and ideally, it should work the same way fuse based projects are expected to work.

**Comment by agowa338** [comment]
> It's possible to do all sort of things but why?

I just wanted to provide you with a way that doesn't block you from moving on with your project. I didn't say anything against implementing such a feature. I'm just also curious why someone would have a need for an applications to daemonize itself.

From your rather short starting post "Nothing to add here." I got the impression that you just want to run it as a service in the background, that's why I suggested to use a systemd unit instead.

Sorry, that I cannot know what you were thinking, I can only respond to information one provides.

**Comment by Bren2010** [comment]
I'm leaning against this for now. You should indeed use a systemd unit or a shell script. That will let you setup forking, decide where logs go, handle crashes, and create PID files or however you intend to let the user stop the process. Those are all things I don't want pulled into this project.

**Comment by mhogomchungu** [comment]
> I just wanted to provide you with a way that doesn't block you from moving on with your project. I didn't say anything against implementing such a feature. I'm just also curious why someone would have a need for an applications to daemonize itself.

This is how FUSE based applications work when they run daemonized.
1. The application starts.
2. Applications checks if all conditions necessary to run are satisfied.
3. If a conditions in step 2 fail, the application prints an error on the terminal and exit with a non zero status result.
4. If all conditions in step 2 pass, the application branches itself into two parts, one part continues as a daemon and the other part returns with a zero result to signify success. 

The point of wanting utahfs to be able to daemonise is because all SiriKali supported backends in Linux and Macos(sshfs, securefs, gocryptfs, cryfs, encfs) have this ability and so far, i have not seen a FUSE based CLI application that does not in Linux.

Initially, i did not add a comment because i didn't think this feature needs convincing and i attributed  a lack of this feature(together with utahfs inability to accept FUSE options) to the youthfulness of this project.

**Comment by mhogomchungu** [comment]
> I'm leaning against this for now. You should indeed use a systemd unit or a shell script. That will let you setup forking, decide where logs go, handle crashes, and create PID files or however you intend to let the user stop the process. Those are all things I don't want pulled into this project.

Your comment seems to suggest utahfs will need assistance from systemd or other external tool to run daemonized and that is not the case and it should be able to do so all by itself. All other FUSE based tools do all by themselves.

gocryptfs[1] for example can run daemonized without assistance from any other tool. The main thread seems to fork[2][3] and that is as far i can go since i cant read the language.

My distro of choice does not use systemd and it will be strange to add systemd or any other system logging dependency to SiriKali.

[1] https://github.com/rfjakob/gocryptfs

[2] https://github.com/rfjakob/gocryptfs/blob/3b61244b72f74a25651d4ba184ac7cc62c937db0/main.go#L154

[3] https://github.com/rfjakob/gocryptfs/blob/3b61244b72f74a25651d4ba184ac7cc62c937db0/daemonize.go#L29

**Comment by Bren2010** [comment]
It's not clear to me why other tools have support for this either, honestly. It's a lot of work and a sure source of compatibility issues, for an inherently bad user experience. Whether it's systemd or circus or something else, all OSes provide some kind of service manager that provides what you need.

**Comment by mhogomchungu** [comment]
Well, when you run "mount" command to mount a file system, it doesn't hang on success.

Not hanging seems to be the default behavior when mounting file systems and FUSE documentation[1] seems to have daemonization as a default behavior.

[1] https://www.kernel.org/doc/html/latest/filesystems/fuse.html

**Comment by mhogomchungu** [comment]
ntfs-3g[1] is an example of project that is based on FUSE and DOES NOT have an option to run it as a foreground process.

[1]  https://wiki.archlinux.org/index.php/NTFS-3G

**Comment by agowa338** [comment]
@Bren2010 sorry for directly mentioning you, but I don't know if this comment gets read otherwise as the issue is already marked as closed.

I think this request could be rephrased as the following requirement: utahfs should be split into two parts. One main part that handles the long standing stuff, that could be a systemd service that runs as soon as the computer/server starts but does not have any configuration itself. And 2nd a small short lived "mount" command that gets called when the user mounts a utahfs fuse filesystem. This command would be responsible for talking to the background service, letting it create the actual mount and return if the background service completed this operation successfully.

This would render explicit forking obsolet but also allow the command that gets invoked by "mount" to be short lived. What do you think?

**Comment by mhogomchungu** [comment]
Lets revisit how file systems work in linux.

With traditional file systems, you:-
1. Mount them using "mount" command.
2. The "mount" command returns immediately.
3. The mounted file system continue to run in a background.
4. The mounted file system is unmounted using "umount" command.

With FUSE based file systems like utahfs, the steps should be the same and should be you:-
1. Mount utahfs file system using "utahfs-client".
2. The "utahfs-client" command returns immediately.
3. The utahfs file system continue to run in a background.
4. The utahfs file system is unmounted using "fusermount" command.

The request here was to make utahfs have a typical behavior of file systems.

Forking and letting the child handle the mounted file system and parent returning immediately is the cleanest solution because:-
1. It causes utahfs to be self sufficient because it wont need systemd or any other tool to start any part of it.
2. One instance of utahfs-client will be managing one instance of a running file system. No need for client-server architecture and the associated complexity as suggested by @agowa338 
3. In my local tests here, a process that is running a mounted file system for cryfs, gocryptfs, securefs, sshfs, encfs, fuseiso, ntfs-3g,exfat and  archivemount is owned by a process with a PID of 1 and this suggests all of them are doing the forking dance and the dance is the standard way of doing it.

![Screenshot_20200626_155756](https://user-images.githubusercontent.com/3496115/85859453-e4020780-b7c5-11ea-8dcf-4042d69d4a73.png)
